[package]
name = "name_generation"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.81"
rand = "0.8.5"
test-case = "3.3.1"
tokio = { version = "1.38.1", features = ["rt","macros"] }
